### ISSUE TITLE
Why not use .tab files?

### ISSUE THREAD

**Issue by mwsasser** [jasonstrooband/alchemy_lex#1]
This is a fun interesting project.

Any chance it will work on standard .tab files eventually?

**Comment by jasonstrooband** [comment]
I do plan on making tab files compatible at some point but there are still quite some features missing for now. One of the biggest ones is nesting commands and other lexical configurations. I have attempted it in the past but it turned into a jumbled mess of errors. I will come back to this at some point because I work on it in bursts.

**Comment by mwsasser** [comment]
Gotcha.  Nice to know.  Thanks for the response.
